name = "aiken-extra/tx_util"
version = "1.140.1013-alpha"
license = "Apache-2.0"
description = "A utility library to help constructing ScriptContext"

[repository]
user = "aiken-extra"
project = "tx_util"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.4.0"
source = "github"
